### ISSUE TITLE
Name 'lanes_points' is not defined

### ISSUE THREAD

**Issue by Yen-Lung-Huang** [ibaiGorordo/TfLite-Ultra-Fast-Lane-Detection-Inference#1]
Hello, thanks for the code. I'm running  "imageLaneDetection.py" with [culan tflite model](https://niuo365-my.sharepoint.com/:u:/g/personal/b0742017_365_niu_edu_tw/EfcDDhZWL2FPk1tc13uvP4sBVM7LtIddm63DTNdPJ86R6Q?e=isX2aO) and change model_type value in imageLaneDetection.py like:
```
model_type = ModelType.CULANE
```

then, i got these on terminal:
```
163: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return np.array(lane_points_mat), np.array(lanes_detected)
Traceback (most recent call last):
  File "imageLaneDetection.py", line 18, in <module>
    output_img = lane_detector.detect_lanes(img)
  File "/home/ubuntu/Codes/TfLite-Ultra-Fast-Lane-Detection-Inference/ultrafastLaneDetector/ultrafastLaneDetector.py", line 82, in detect_lanes
    visualization_img = self.draw_lanes(image, self.lanes_points, self.lanes_detected, self.cfg, draw_points)
  File "/home/ubuntu/Codes/TfLite-Ultra-Fast-Lane-Detection-Inference/ultrafastLaneDetector/ultrafastLaneDetector.py", line 175, in draw_lanes
    cv2.fillPoly(lane_segment_img, pts = [np.vstack((lanes_points[1],np.flipud(lanes_points[2])))], color =(255,191,0))
NameError: name 'lanes_points' is not defined
```
 
![image](https://user-images.githubusercontent.com/73886748/154525391-cb4381ea-7d70-4839-a6e6-39acf022f2c9.png)

is the error message means the "lanes_points" variable in ultrafastLaneDetector.py is not defined? Where should I define the "lanes_points" in code?

**Comment by ibaiGorordo** [comment]
yeah, that should have been lane_points_mat instead of lanes_points (I copy pasted this part from my other repository, but forgot to modify it).

I think it should work now.

**Comment by Yen-Lung-Huang** [comment]
Yes, it works well! Thank you very much.
![image](https://user-images.githubusercontent.com/73886748/160232900-58319fec-2607-4de6-a70c-c54d0d0fa800.png)
